print("ヤドンだよー！！！")
print("killコマンドは許しません！！！")
while(True):
    print("        _.--'"'--'"'--._ ")
    print("      .'            `.")
    print("     /   .--.  .--.   \ ")
    print("    |   ( 'o' )( 'o' ) |")
    print("    |    `----'`----'  |")
    print("    \      ______      /")
    print("     \    (______)    /")
    print("      `.            .'")
    print("        `--......--'")
    print("           /    \ ")
    print("          /      \ ")
    print("         (        )")
    print("          `------'")
    print("ヤドンはかわいいなぁ～")
    print("Ctrl+Cで強制終了しないでね！！！")
    print("ヤドンはあなたのことを信じてるんだよ！！！")